# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, 和 support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Jekyll Site CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.6

    - name: Add platform to lockfile
      run: bundle lock --add-platform x86_64-linux

    - name: Install dependencies
      run: bundle install --jobs 4

    - name: Build the site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      run: bundle exec jekyll deploy
        
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
